#!/bin/bash
docker stop webuseworker1
docker stop webuseworker1
docker rm webuseworker1 
docker stop webuseworker2
docker rm webuseworker2 
docker stop webuseworker3
docker rm webuseworker3 
docker stop webuseworker4
docker rm webuseworker4 
docker stop webuseworker5
docker stop webuseworker6
docker rm webuseworker5 
docker rm webuseworker6
docker stop webuseworker7 
docker rm webuseworker7  
docker rm webuseworker8 
docker stop webuseworker8
docker rm webuseworker9 
docker stop webuseworker10
docker rm webuseworker10
docker stop webuseworker11
docker rm webuseworker11
docker stop webuseworker12
docker stop webuseworker13
docker rm webuseworker12
docker rm webuseworker13
docker stop webuseworker14 
docker rm webuseworker14
